import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { MarsiaShell } from "@/components/marsia-shell";

function NotFoundComponent(){return <div className="grid min-h-screen place-items-center bg-background p-6 text-center"><div><div className="font-display text-8xl text-primary">404</div><h1 className="font-display text-3xl uppercase">Coordenada não encontrada</h1><p className="mt-2 text-sm text-muted-foreground">Este setor ainda não foi mapeado.</p><Link to="/" className="action-button mt-6">Voltar ao comando</Link></div></div>}
function ErrorComponent({error,reset}:{error:Error;reset:()=>void}){console.error(error);const router=useRouter();useEffect(()=>{reportLovableError(error,{boundary:"tanstack_root_error_component"})},[error]);return <div className="grid min-h-screen place-items-center bg-background p-6 text-center"><div><h1 className="font-display text-4xl uppercase">Sinal interrompido</h1><p className="mt-2 text-sm text-muted-foreground">Não foi possível carregar este setor.</p><button className="action-button mt-6" onClick={()=>{router.invalidate();reset()}}>Restabelecer conexão</button></div></div>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:"utf-8"},{name:"viewport",content:"width=device-width, initial-scale=1"},{title:"MARSIA — Exploração Social de Marte"},{name:"description",content:"Explore Marte, registre territórios simbólicos e participe de missões em uma comunidade de outro mundo."},{property:"og:title",content:"MARSIA — Exploração Social de Marte"},{property:"og:description",content:"Seu primeiro território em outro mundo."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}],links:[{rel:"stylesheet",href:appCss},{rel:"preconnect",href:"https://fonts.googleapis.com"},{rel:"preconnect",href:"https://fonts.gstatic.com",crossOrigin:"anonymous"},{rel:"stylesheet",href:"https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;600;700&family=IBM+Plex+Mono:wght@400;500&family=Space+Grotesk:wght@400;500;600&display=swap"},{rel:"icon",href:"/favicon.ico",type:"image/x-icon"}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFoundComponent,errorComponent:ErrorComponent});
function RootShell({children}:{children:ReactNode}){return <html lang="pt-BR"><head><HeadContent/></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();return <QueryClientProvider client={queryClient}><MarsiaShell><Outlet/></MarsiaShell></QueryClientProvider>}
