import { Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { toast } from "sonner";
import { Activity, Antenna, ArrowRight, Atom, Bot, Check, ChevronRight, CircleDot, Compass, Dna, FlaskConical, Gauge, Globe2, Headphones, Hexagon, Leaf, Lock, MapPin, Mountain, Orbit, Radio, Rocket, Satellite, ScanLine, Shield, Sparkles, Star, Telescope, Users, Waves } from "lucide-react";
import marsMap from "@/assets/mars-map.jpg";
import { useMarsia } from "@/lib/marsia-context";
import { ActionLink, ActivityDot, CommsRoom, Eyebrow, PageHeader, Panel, Progress, Stat, Structure } from "@/components/ui";

const regions = [
  { name: "Olympus Mons", x: 20, y: 29 }, { name: "Valles Marineris", x: 42, y: 58 },
  { name: "Elysium Planitia", x: 72, y: 35, featured: true }, { name: "Utopia", x: 81, y: 21 },
  { name: "Gale", x: 63, y: 66 }, { name: "Hellas", x: 80, y: 77 },
];

export function DashboardPage() {
  const { baseName, acquired } = useMarsia();
  return <><div className="mb-8 flex items-center justify-between"><div className="flex items-center gap-3 text-xs text-muted-foreground"><ActivityDot/>18 exploradores ativos em Marte</div><div className="hidden font-mono text-[10px] text-muted-foreground sm:block">COORD // 4.5°N 135.9°E</div></div>
    <div className="grid gap-7 xl:grid-cols-[1.3fr_.7fr]"><div><Eyebrow>Centro de comando / Sol 0451</Eyebrow><h1 className="mt-4 max-w-3xl font-display text-5xl uppercase leading-[.92] md:text-7xl">Bem-vindo de volta, <span className="text-primary">explorador.</span></h1><p className="mt-5 max-w-xl text-sm leading-6 text-muted-foreground">Seu primeiro território em outro mundo. Continue sua jornada por Elysium e expanda sua presença marciana.</p></div>
    <Panel className="relative overflow-hidden p-6"><div className="absolute right-0 top-0 size-28 border-b border-l border-primary/20 bg-primary/5"/><Eyebrow>Identidade ativa</Eyebrow><div className="mt-5 flex items-center gap-4"><div className="grid size-14 place-items-center border border-primary/40 bg-primary/10"><Hexagon className="text-primary"/></div><div><div className="font-display text-xl uppercase">Marcos Almeida</div><div className="text-xs text-muted-foreground">Pioneer // Explorer ID 07-1142</div></div></div><div className="mt-6 flex items-end justify-between"><span className="text-xs text-muted-foreground">Nível 12</span><span className="font-mono text-xs text-primary">7.450 / 9.000 XP</span></div><div className="mt-2"><Progress value={82}/></div></Panel></div>

    <div className="mt-10 grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4"><div className="bg-card p-5"><Stat label="Território atual" value={acquired ? baseName : "M-042"} sub={acquired ? "Registro confirmado" : "Disponível para registro"}/></div><div className="bg-card p-5"><Stat label="Região" value="Elysium" sub="Planitia // Setor 04"/></div><div className="bg-card p-5"><Stat label="Área mapeada" value="2.500 m²" sub="Território raro"/></div><div className="bg-card p-5"><Stat label="Missões" value="08 / 12" sub="Taxa de sucesso 94%"/></div></div>

    <div className="mt-8 grid gap-6 lg:grid-cols-[1.3fr_.7fr]"><Panel className="mission-hero p-6 md:p-8"><div className="relative z-10 max-w-xl"><div className="flex items-center gap-2"><Rocket size={15} className="text-primary"/><Eyebrow>Missão ativa / 03</Eyebrow></div><h2 className="mt-8 font-display text-4xl uppercase md:text-5xl">Expedição<br/>Elysium</h2><p className="mt-4 max-w-md text-sm leading-6 text-muted-foreground">Uma nova área foi identificada próxima ao seu território. Analise os sinais e lidere a primeira incursão.</p><div className="mt-8"><ActionLink to="/missoes">Entrar na expedição</ActionLink></div></div></Panel>
    <Panel className="p-6"><div className="flex items-center justify-between"><Eyebrow>Atividade em Marte</Eyebrow><ActivityDot/></div><div className="mt-8 font-display text-5xl">18</div><p className="mt-1 text-sm text-muted-foreground">exploradores estão ativos agora.</p><div className="mt-7 space-y-4">{["Elysium Planitia","Olympus Mons","Valles Marineris"].map((r,i)=><div key={r} className="flex items-center justify-between border-t border-border pt-3 text-xs"><span className="text-muted-foreground">{r}</span><span className="font-mono">{[8,6,4][i]} online</span></div>)}</div><div className="mt-6"><ActionLink to="/comunidade">Abrir comunidade</ActionLink></div></Panel></div></>;
}

export function ExplorePage() {
  const [selected, setSelected] = useState("Elysium Planitia");
  return <><PageHeader code="Atlas planetário / 02" title="Explorar Marte" description="Navegue por regiões catalogadas, identifique sinais e encontre seu ponto de entrada em outro mundo."/>
    <div className="relative min-h-[590px] overflow-hidden border border-border bg-card"><img src={marsMap} alt="Mapa topográfico orbital de Marte" width={1920} height={1080} className="absolute inset-0 size-full object-cover opacity-75"/><div className="map-overlay absolute inset-0"/><div className="absolute left-4 top-4 z-10 border border-border bg-background/80 p-4 backdrop-blur-md"><Eyebrow>MARS // GLOBAL SURVEY</Eyebrow><div className="mt-2 flex items-center gap-2 font-mono text-[10px] text-muted-foreground"><ScanLine size={13}/>Mapeamento 67.4%</div></div>
    <div className="absolute right-4 top-4 z-10 hidden border border-border bg-background/80 p-4 text-right backdrop-blur-md sm:block"><div className="font-mono text-[9px] text-muted-foreground">ALTITUDE ORBITAL</div><div className="mt-1 font-display text-xl">384 KM</div></div>
    {regions.map(region => <button key={region.name} onClick={()=>setSelected(region.name)} aria-label={`Selecionar ${region.name}`} className={`map-marker ${selected===region.name ? "map-marker-active" : ""}`} style={{left:`${region.x}%`,top:`${region.y}%`}}><span/><b>{region.name}</b></button>)}
    <div className="absolute bottom-0 left-0 right-0 z-10 grid gap-4 border-t border-border bg-background/88 p-4 backdrop-blur-xl md:grid-cols-[1fr_auto] md:items-center md:p-6"><div><div className="flex items-center gap-2"><CircleDot size={14} className="text-primary"/><span className="font-mono text-[10px] uppercase tracking-[.16em] text-primary">Região selecionada</span></div><div className="mt-2 font-display text-2xl uppercase">{selected}</div></div>{selected==="Elysium Planitia" ? <Link to="/territorio/$territoryId" params={{territoryId:"M-042"}} className="action-button">Ver território M-042 <ArrowRight size={15}/></Link> : <button className="secondary-button" onClick={()=>toast.info("Escaneamento iniciado",{description:`Novos sinais serão analisados em ${selected}.`})}>Escanear região <ScanLine size={15}/></button>}</div></div>
    <div className="mt-6 grid gap-4 md:grid-cols-3">{[{id:"M-042",area:"2.500 m²",rare:"Raro",available:true},{id:"M-018",area:"1.800 m²",rare:"Incomum"},{id:"M-077",area:"4.200 m²",rare:"Épico"}].map((t,i)=><Panel key={t.id} className={`p-5 ${!t.available ? "opacity-55" : ""}`}><div className="flex items-center justify-between"><span className="font-mono text-xs text-primary">{t.id}</span><span className="text-[9px] uppercase tracking-[.16em] text-muted-foreground">{t.available?"Disponível":"Sob análise"}</span></div><div className="mt-7 font-display text-2xl">{t.area}</div><div className="mt-1 text-xs text-muted-foreground">Elysium // {t.rare}</div>{i===0 && <div className="mt-5"><Link to="/territorio/$territoryId" params={{territoryId:"M-042"}} className="text-link">Ver território <ChevronRight size={14}/></Link></div>}</Panel>)}</div></>;
}

export function TerritoryPage() {
  const { acquired, baseName, acquire } = useMarsia(); const navigate=useNavigate();
  const [modal,setModal]=useState(false); const [step,setStep]=useState<"confirm"|"naming">("confirm"); const [name,setName]=useState(baseName); const [loading,setLoading]=useState(false);
  const confirm=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setStep("naming")},900)};
  const finish=()=>{acquire(name.trim()||"Base Aurora");setModal(false);navigate({to:"/minha-base"})};
  return <><PageHeader code="Registro territorial / M-042" title="Elysium M-042" description="Uma posição estratégica em uma planície vulcânica catalogada pela rede MARSIA."/>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[520px] overflow-hidden border border-border"><img src={marsMap} alt="Vista orbital do território M-042 em Elysium Planitia" width={1920} height={1080} className="absolute inset-0 size-full object-cover"/><div className="territory-scan absolute inset-[12%] border border-primary/70"><span className="absolute -left-px -top-px size-4 border-l-2 border-t-2 border-primary"/><span className="absolute -bottom-px -right-px size-4 border-b-2 border-r-2 border-primary"/><div className="absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 text-center"><MapPin className="mx-auto text-primary"/><div className="mt-2 bg-background/80 px-3 py-2 font-mono text-[10px] uppercase text-primary backdrop-blur">M-042 // Locked</div></div></div><div className="absolute bottom-4 left-4 font-mono text-[9px] text-foreground">4.5°N / 135.9°E<br/>ALT +1.2 KM</div></div>
    <Panel className="p-6 md:p-8"><div className="flex items-center justify-between"><Eyebrow>Status do registro</Eyebrow><span className={`status-pill ${acquired ? "status-owned" : ""}`}>{acquired?"Adquirido":"Disponível"}</span></div><div className="mt-10 grid grid-cols-2 gap-7"><Stat label="Área" value="2.500 m²"/><Stat label="Raridade" value="Raro"/><Stat label="Região" value="Elysium"/><Stat label="Elevação" value="+1.2 km"/></div><div className="mt-9 border-t border-border pt-6"><div className="flex justify-between text-xs"><span className="text-muted-foreground">Nível de exploração</span><span className="font-mono text-primary">42%</span></div><div className="mt-3"><Progress value={42}/></div></div><div className="mt-8">{acquired?<ActionLink to="/minha-base">Acessar {baseName}</ActionLink>:<button className="action-button w-full" onClick={()=>{setStep("confirm");setModal(true)}}>Adquirir território <ArrowRight size={15}/></button>}</div><p className="mt-4 text-[10px] leading-4 text-muted-foreground">Registro conceitual e simbólico. Nenhuma propriedade imobiliária real é transferida.</p></Panel></div>
    <div className="mt-6 grid gap-4 md:grid-cols-3">{[{icon:Mountain,title:"Formação vulcânica",text:"Afloramento basáltico a 3,2 km"},{icon:Waves,title:"Sinal subterrâneo",text:"Anomalia mineral não classificada"},{icon:Satellite,title:"Cobertura orbital",text:"Conexão estável com Relay-7"}].map(({icon:Icon,title,text})=><Panel key={title} className="p-5"><Icon size={19} className="text-primary"/><div className="mt-6 font-display text-lg uppercase">{title}</div><p className="mt-1 text-xs text-muted-foreground">{text}</p></Panel>)}</div>
    {modal&&<div className="modal-backdrop"><div role="dialog" aria-modal="true" className="modal-panel">{step==="confirm"?<><Eyebrow>Protocolo de aquisição</Eyebrow><h2 className="mt-4 font-display text-4xl uppercase">Registrar M-042?</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Este registro simbólico adicionará o território à sua identidade MARSIA e desbloqueará a criação da sua base.</p><div className="mt-6 border border-border bg-muted/40 p-4"><div className="flex justify-between text-sm"><span>Elysium // 2.500 m²</span><span className="font-mono text-primary">R$ 99</span></div></div><div className="mt-7 flex gap-3"><button className="secondary-button flex-1" onClick={()=>setModal(false)}>Cancelar</button><button className="action-button flex-1" disabled={loading} onClick={confirm}>{loading?"Validando sinal...":"Confirmar registro"}</button></div></>:<><div className="grid size-12 place-items-center border border-signal/40 bg-signal/10"><Check className="text-signal"/></div><h2 className="mt-5 font-display text-4xl uppercase">Seu território foi registrado</h2><p className="mt-3 text-sm text-muted-foreground">Defina a identificação oficial da sua primeira base marciana.</p><label className="mt-7 block text-[10px] uppercase tracking-[.16em] text-muted-foreground">Nome da base</label><input autoFocus value={name} maxLength={28} onChange={e=>setName(e.target.value)} className="mars-input"/><button className="action-button mt-5 w-full" onClick={finish}>Ativar base <ArrowRight size={15}/></button></>}</div></div>}</>;
}
