import { useState } from "react";
import { toast } from "sonner";
import { Antenna, Atom, Bot, Check, ChevronRight, Compass, Dna, Fingerprint, FlaskConical, Globe2, Headphones, Hexagon, Leaf, Lock, MapPin, Medal, Orbit, Radio, Rocket, Satellite, Shield, Sparkles, Star, Telescope, Users } from "lucide-react";
import { useMarsia } from "@/lib/marsia-context";
import { ActionLink, ActivityDot, CommsRoom, Eyebrow, PageHeader, Panel, Progress, Stat, Structure } from "@/components/ui";

export function BasePage(){
  const {acquired,baseName,renameBase}=useMarsia(); const [editing,setEditing]=useState(false); const [name,setName]=useState(baseName);
  if(!acquired)return <><PageHeader code="Base operacional / Offline" title="Nenhuma base ativa" description="Seu centro de operações será desbloqueado depois que você registrar o primeiro território."/><Panel className="grid min-h-[420px] place-items-center p-8 text-center"><div><Orbit className="mx-auto text-primary" size={54}/><h2 className="mt-6 font-display text-3xl uppercase">Aguardando coordenadas</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Explore Elysium, selecione o território M-042 e conclua o registro para iniciar sua base.</p><div className="mt-7"><ActionLink to="/explorar">Explorar Marte</ActionLink></div></div></Panel></>;
  return <><PageHeader code="Base operacional / M-042" title={baseName} description="Seu primeiro ponto permanente de exploração em Elysium Planitia."/>
    <div className="grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Panel className="relative min-h-[360px] overflow-hidden p-7 md:p-10"><div className="absolute inset-0 passport-grid opacity-30"/><div className="absolute -right-28 top-1/2 size-[360px] -translate-y-1/2 rounded-full border border-primary/30 shadow-[0_0_80px_color-mix(in_oklab,var(--primary)_12%,transparent)]"><div className="absolute inset-10 rounded-full border border-primary/20"><div className="absolute inset-12 rounded-full border border-primary/15"/></div></div><div className="relative z-10"><div className="flex items-center gap-2"><ActivityDot/><Eyebrow>Todos os sistemas nominais</Eyebrow></div><div className="mt-16 font-mono text-[10px] uppercase tracking-[.18em] text-muted-foreground">Estágio atual</div><h2 className="mt-3 max-w-lg font-display text-4xl uppercase md:text-5xl">Nível 1 — Território descoberto</h2><div className="mt-8 max-w-md"><div className="mb-3 flex justify-between text-xs"><span>Próximo nível: Território explorado</span><span className="font-mono text-primary">42%</span></div><Progress value={42}/></div></div></Panel>
    <Panel className="p-7"><Eyebrow>Telemetria da base</Eyebrow><div className="mt-8 grid grid-cols-2 gap-7"><Stat label="Região" value="Elysium"/><Stat label="Área" value="2.500 m²"/><Stat label="Nível" value="01"/><Stat label="Base XP" value="1.240"/></div><div className="mt-8 border-t border-border pt-6">{editing?<><label className="text-[10px] uppercase tracking-[.15em] text-muted-foreground">Nova identificação</label><input value={name} onChange={e=>setName(e.target.value)} maxLength={28} className="mars-input"/><div className="mt-3 flex gap-2"><button className="secondary-button flex-1" onClick={()=>{setName(baseName);setEditing(false)}}>Cancelar</button><button className="action-button flex-1" onClick={()=>{renameBase(name.trim()||baseName);setEditing(false)}}>Salvar</button></div></>:<button className="secondary-button w-full" onClick={()=>setEditing(true)}>Renomear base</button>}</div></Panel></div>
    <div className="mt-8"><div className="mb-4 flex items-center justify-between"><div><Eyebrow>Módulos estruturais</Eyebrow><h2 className="mt-2 font-display text-2xl uppercase">Estruturas da base</h2></div><span className="font-mono text-[10px] text-muted-foreground">02 / 04 DISPONÍVEIS</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Structure icon={Bot} name="Habitat" detail="Módulo operacional"/><Structure icon={FlaskConical} name="Laboratório" detail="Desbloqueia no nível 2" locked/><Structure icon={Antenna} name="Antena" detail="Sinal orbital estável"/><Structure icon={Leaf} name="Estufa" detail="Desbloqueia no nível 3" locked/></div></div></>;
}

const missions=[
 {code:"MX-12",title:"Expedição Olympus",type:"Exploração",difficulty:3,desc:"Investigar uma região próxima ao Olympus Mons.",reward:"+500 XP",icon:Telescope},
 {code:"MX-09",title:"Sinais de Elysium",type:"Análise",difficulty:2,desc:"Decodificar pulsos detectados ao norte da sua base.",reward:"+320 XP",icon:Satellite},
 {code:"MX-18",title:"Abismo de Valles",type:"Reconhecimento",difficulty:5,desc:"Mapear uma rota no maior cânion do sistema solar.",reward:"+1.200 XP",icon:Compass,locked:true},
];
export function MissionsPage(){const [active,setActive]=useState("MX-12");return <><PageHeader code="Operações / 04" title="Missões" description="Expedições coletivas ampliam seu mapa, sua reputação e o alcance da comunidade MARSIA."/><div className="grid gap-5 lg:grid-cols-3">{missions.map(({code,title,type,difficulty,desc,reward,icon:Icon,locked})=><Panel key={code} className={`flex min-h-[370px] flex-col p-6 ${locked?"opacity-50":""}`}><div className="flex items-center justify-between"><span className="font-mono text-[10px] text-primary">{code}</span>{locked?<Lock size={15}/>:active===code?<span className="text-[9px] uppercase tracking-[.14em] text-signal">Missão ativa</span>:<span className="text-[9px] uppercase tracking-[.14em] text-muted-foreground">Disponível</span>}</div><Icon className="mt-10 text-primary" size={28}/><div className="mt-6 text-[10px] uppercase tracking-[.16em] text-muted-foreground">{type}</div><h2 className="mt-2 font-display text-3xl uppercase">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p><div className="mt-auto pt-8"><div className="flex justify-between border-t border-border pt-4 text-xs"><span>Dificuldade <b className="text-foreground">{difficulty}/5</b></span><span className="font-mono text-primary">{reward}</span></div><button disabled={locked} className={locked?"secondary-button mt-5 w-full":"action-button mt-5 w-full"} onClick={()=>{if(!locked){setActive(code);toast.success("Expedição iniciada",{description:`Você entrou em ${title}.`})}}}>{locked?"Requer nível 15":active===code?"Em andamento":"Entrar na expedição"}</button></div></Panel>)}</div>
  <Panel className="mt-6 grid gap-6 p-6 md:grid-cols-[auto_1fr_auto] md:items-center"><div className="grid size-14 place-items-center border border-primary/30 bg-primary/10"><Rocket className="text-primary"/></div><div><Eyebrow>Progresso da temporada</Eyebrow><div className="mt-2 text-sm">8 de 12 missões concluídas no ciclo Elysium.</div><div className="mt-3"><Progress value={66}/></div></div><div className="font-display text-3xl text-primary">66%</div></Panel></>}

export function PassportPage(){const {acquired,baseName}=useMarsia();return <><PageHeader code="Identidade MARSIA / 06" title="Meu Passaporte" description="Registro digital de exploração, territórios e feitos reconhecidos pela comunidade."/><div className="mx-auto max-w-5xl border border-border bg-card"><div className="grid lg:grid-cols-[.8fr_1.2fr]"><div className="relative overflow-hidden border-b border-border p-7 lg:border-b-0 lg:border-r"><div className="absolute inset-0 passport-grid opacity-20"/><div className="relative"><div className="flex items-center justify-between"><Hexagon className="text-primary" size={32}/><span className="font-mono text-[9px] uppercase tracking-[.18em] text-muted-foreground">Valid // 2034</span></div><div className="mt-12 grid aspect-[4/5] place-items-center border border-border bg-background/70"><div className="relative grid size-40 place-items-center border border-primary/30"><Fingerprint size={82} className="text-primary opacity-75"/><span className="absolute -bottom-7 font-mono text-[9px] text-muted-foreground">BIO-ID VERIFIED</span></div></div><div className="mt-10 flex items-center gap-2 font-mono text-[10px] uppercase text-signal"><Check size={13}/>Identidade verificada</div></div></div>
    <div className="p-7 md:p-10"><Eyebrow>Mars Citizen Network</Eyebrow><h2 className="mt-5 font-display text-5xl uppercase md:text-6xl">Marcos<br/>Almeida</h2><div className="mt-2 font-mono text-xs uppercase tracking-[.18em] text-primary">Marsia Explorer // Pioneer</div><div className="mt-10 grid grid-cols-2 gap-7"><Stat label="Território" value={acquired?"M-042":"Pendente"}/><Stat label="Região" value="Elysium"/><Stat label="Área" value={acquired?"2.500 m²":"—"}/><Stat label="Nível" value="12"/></div><div className="mt-10 border-t border-border pt-7"><div className="mb-4 text-[10px] uppercase tracking-[.16em] text-muted-foreground">Conquistas registradas</div><div className="flex flex-wrap gap-3">{[{i:Star,n:"Pioneer"},{i:Rocket,n:"First Launch"},{i:Shield,n:"Elysium"},{i:Medal,n:"8 Missions"}].map(({i:Icon,n})=><div key={n} className="flex items-center gap-2 border border-border bg-muted/40 px-3 py-2 text-xs"><Icon size={14} className="text-primary"/>{n}</div>)}</div></div>{acquired&&<div className="mt-8 text-xs text-muted-foreground">Base vinculada: <span className="text-foreground">{baseName}</span></div>}</div></div><div className="flex flex-wrap items-center justify-between gap-4 border-t border-border px-7 py-4 font-mono text-[9px] uppercase tracking-[.13em] text-muted-foreground"><span>MRS-07-1142-ELYS</span><span>Earth–Mars identity protocol</span></div></div></>}

export function CommunityPage(){return <><PageHeader code="Rede social orbital / 05" title="Comunidade" description="Acompanhe descobertas, expedições e transmissões de exploradores distribuídos por Marte."/>
  <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><div className="space-y-4">{[
   {icon:Users,time:"AGORA",text:"18 exploradores estão em Elysium.",meta:"Atividade regional em alta"},
   {icon:Rocket,time:"04 MIN",text:"Uma nova expedição foi criada.",meta:"Expedição Olympus // MX-12"},
   {icon:Star,time:"18 MIN",text:"Luna completou sua 20ª missão.",meta:"Conquista: Veteran Pathfinder"},
   {icon:Globe2,time:"36 MIN",text:"Elysium Explorers descobriu uma nova área.",meta:"Setor classificado como ELY-X09"},
  ].map(({icon:Icon,time,text,meta},i)=><Panel key={text} className="group p-5 transition-colors hover:border-primary/40"><div className="flex gap-4"><div className="grid size-10 shrink-0 place-items-center border border-border bg-muted"><Icon size={17} className={i===0?"text-signal":"text-primary"}/></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><span className="text-sm">{text}</span><span className="shrink-0 font-mono text-[9px] text-muted-foreground">{time}</span></div><div className="mt-2 text-xs text-muted-foreground">{meta}</div></div></div></Panel>)}</div>
  <div className="space-y-6"><Panel className="p-6"><div className="flex items-center justify-between"><Eyebrow>Equipe em destaque</Eyebrow><Shield size={18} className="text-primary"/></div><div className="mt-8 flex items-center gap-4"><div className="grid size-14 place-items-center border border-primary/40 bg-primary/10"><Hexagon className="text-primary"/></div><div><h2 className="font-display text-2xl uppercase">Elysium Explorers</h2><p className="text-xs text-muted-foreground">Fundada no Sol 0182</p></div></div><div className="mt-7 grid grid-cols-2 gap-5"><Stat label="Membros" value="23"/><Stat label="Missões" value="14"/></div><button className="secondary-button mt-7 w-full" onClick={()=>toast.info("Perfil da equipe carregado",{description:"23 exploradores conectados à rede Elysium."})}>Ver equipe <ChevronRight size={14}/></button></Panel>
  <Panel className="p-6"><div className="flex items-center justify-between"><div><Eyebrow>Mars Comms</Eyebrow><h2 className="mt-2 font-display text-2xl uppercase">Canais ao vivo</h2></div><Headphones className="text-primary"/></div><div className="mt-4"><CommsRoom name="Mission Control" count={18}/><CommsRoom name="Olympus Expedition" count={7}/><CommsRoom name="Mars Science Lab" count={5}/></div><p className="mt-4 text-[10px] leading-4 text-muted-foreground">Salas simuladas para demonstração. Transmissão de áudio indisponível neste protótipo.</p></Panel></div></div></>}
